In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
train_data = pd.read_csv('train.csv')
y = train_data['y'].to_numpy()
X = train_data.iloc[:, 2:].to_numpy()

In [3]:
X_6_10 = np.square(X)
print(X_6_10)
X_11_15 = np.exp(X)
X_16_20 = np.cos(X)
X_21 = np.ones((np.shape(X)[0],1))
Features = np.hstack((X, X_6_10, X_11_15, X_16_20, X_21))

[[4.000e-04 2.500e-03 8.100e-03 1.849e-01 6.400e-03]
 [1.690e-02 1.210e-02 6.400e-03 8.410e-02 9.000e-04]
 [6.400e-03 3.600e-03 4.900e-03 1.681e-01 9.000e-04]
 ...
 [7.290e-02 4.840e-02 1.000e-04 1.024e-01 2.500e-03]
 [3.610e-02 1.210e-02 2.500e-03 7.290e-02 1.600e-03]
 [8.100e-03 8.100e-03 3.600e-03 1.681e-01 3.600e-03]]


In [4]:
reg = LinearRegression(fit_intercept=False).fit(Features, y)
np.savetxt("submission.csv", reg.coef_, delimiter=" ")

The code is fundamentally divided in 4 parts. I've used a notebook for the ease of visualization of the output of each section.

First part are the import, I used sklearn linear regression to perform indeed the regression.
 For the second part I used pandas to import the .csv train file from the same folder and there split train and data in to separate numpy arrays.

Third section we used the element wise NumPy Mathematical functions to transform the linear input data in non linear features, we add as requested a row of ones and then hstack to put aside the column vector made by non linear features.

Finally we perform regression with the whole training dataset, using fit_intercept = false since we have a bias and we do not want to fit the observations around zero. Finally we export the weights on the submission file.